<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vm_base"
 *
 * Auto generated by Extension Builder 2018-02-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SmartVerein - Base module',
    'description' => 'Basic functions for SmartVerein club management.',
    'category' => 'plugin',
    'author' => 'Typo3graf Developer-Team',
    'author_email' => 'development@typo3graf.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => 'fileadmin/smartverein/',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
