<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vm_dashboard"
 *
 * Auto generated by Extension Builder 2018-02-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SmartVerein - Dashboard module',
    'description' => 'Dashboard module for SmartVerein.',
    'category' => 'plugin',
    'author' => 'Typo3graf Developer-Team',
    'author_email' => 'development@typo3graf.de',
    'author_company' => 'Typo3graf media-agentur',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'dyncss_less' => '*',
            'vm_club' => '*',
            'vm_member' => '*',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' =>
        [
            'psr-4' =>
                [
                    'Typo3graf\\VmDashboard\\' => 'Classes'
                ]
        ]
];
