DROP TABLE IF EXISTS `fe_groups`;
CREATE TABLE `fe_groups` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tx_extbase_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pid` int(10) unsigned NOT NULL DEFAULT '0',
  `tstamp` int(10) unsigned NOT NULL DEFAULT '0',
  `crdate` int(10) unsigned NOT NULL DEFAULT '0',
  `cruser_id` int(10) unsigned NOT NULL DEFAULT '0',
  `title` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `hidden` smallint(5) unsigned NOT NULL DEFAULT '0',
  `lockToDomain` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `deleted` smallint(5) unsigned NOT NULL DEFAULT '0',
  `description` text COLLATE utf8_unicode_ci,
  `subgroup` tinytext COLLATE utf8_unicode_ci,
  `TSconfig` text COLLATE utf8_unicode_ci,
  `felogin_redirectPid` tinytext COLLATE utf8_unicode_ci,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `fe_groups` (`uid`, `tx_extbase_type`, `pid`, `tstamp`, `crdate`, `cruser_id`, `title`, `hidden`, `lockToDomain`, `deleted`, `description`, `subgroup`, `TSconfig`, `felogin_redirectPid`) VALUES
(1,	'0',	42,	1520757772,	1520243365,	1,	'Mitgliederverwaltung',	0,	'',	0,	'',	'',	'',	'5'),
(2,	'0',	42,	1520757788,	1520243384,	1,	'Terminverwaltung',	0,	'',	0,	'',	'',	'',	'5'),
(3,	'0',	42,	1520757804,	1520243416,	1,	'Aufgabenverwaltung',	0,	'',	0,	'',	'',	'',	'15'),
(4,	'0',	42,	1520757855,	1520757748,	1,	'Versammlungsplaner',	0,	'',	0,	'',	'',	'',	''),
(5,	'0',	42,	1520757870,	1520757870,	1,	'Buchhaltung',	0,	'',	0,	'',	'',	'',	''),
(6,	'0',	42,	1520757904,	1520757904,	1,	'Adressbuch',	0,	'',	0,	'',	'',	'',	''),
(7,	'0',	42,	1520757923,	1520757923,	1,	'Schriftverkehr',	0,	'',	0,	'',	'',	'',	''),
(8,	'0',	42,	1520757941,	1520757941,	1,	'Inventarverwaltung',	0,	'',	0,	'',	'',	'',	''),
(9,	'0',	42,	1520757972,	1520757972,	1,	'Dateiverwaltung',	0,	'',	0,	'',	'',	'',	''),
(10,	'0',	42,	1520758018,	1520758018,	1,	'Mein Verein',	0,	'',	0,	'',	'',	'',	''),
(11,	'0',	42,	1520758033,	1520758033,	1,	'Einstellungen',	0,	'',	0,	'',	'',	'',	''),
(12,	'0',	42,	1520759493,	1520759021,	1,	'Mitglied',	0,	'',	0,	'',	'',	'',	'15'),
(13,	'0',	42,	1525110297,	1520758806,	1,	'Alle Berechtigungen',	0,	'',	0,	'',	'6,3,5,9,11,8,10,1,7,2,4,12',	'',	'5'),
(14,	'0',	42,	1525110327,	1520759078,	1,	'Vorstand',	0,	'',	0,	'',	'6,3,9,8,10,1,7,2,4,12',	'',	'');

DROP TABLE IF EXISTS `fe_users`;
CREATE TABLE `fe_users` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tx_extbase_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `pid` int(10) unsigned NOT NULL DEFAULT '0',
  `tstamp` int(10) unsigned NOT NULL DEFAULT '0',
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `password` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `usergroup` tinytext COLLATE utf8_unicode_ci,
  `disable` smallint(5) unsigned NOT NULL DEFAULT '0',
  `starttime` int(10) unsigned NOT NULL DEFAULT '0',
  `endtime` int(10) unsigned NOT NULL DEFAULT '0',
  `name` varchar(160) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `first_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `middle_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `last_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `address` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `telephone` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fax` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `crdate` int(10) unsigned NOT NULL DEFAULT '0',
  `cruser_id` int(10) unsigned NOT NULL DEFAULT '0',
  `lockToDomain` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `deleted` smallint(5) unsigned NOT NULL DEFAULT '0',
  `description` text COLLATE utf8_unicode_ci,
  `uc` blob,
  `title` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `zip` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `city` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `country` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `www` varchar(80) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `company` varchar(80) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `image` tinytext COLLATE utf8_unicode_ci,
  `TSconfig` text COLLATE utf8_unicode_ci,
  `lastlogin` int(10) unsigned NOT NULL DEFAULT '0',
  `is_online` int(10) unsigned NOT NULL DEFAULT '0',
  `felogin_redirectPid` tinytext COLLATE utf8_unicode_ci,
  `felogin_forgotHash` varchar(80) COLLATE utf8_unicode_ci DEFAULT '',
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`,`username`),
  KEY `username` (`username`),
  KEY `is_online` (`is_online`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `fe_users` (`uid`, `tx_extbase_type`, `pid`, `tstamp`, `username`, `password`, `usergroup`, `disable`, `starttime`, `endtime`, `name`, `first_name`, `middle_name`, `last_name`, `address`, `telephone`, `fax`, `email`, `crdate`, `cruser_id`, `lockToDomain`, `deleted`, `description`, `uc`, `title`, `zip`, `city`, `country`, `www`, `company`, `image`, `TSconfig`, `lastlogin`, `is_online`, `felogin_redirectPid`, `felogin_forgotHash`) VALUES
(1,	'0',	45,	1529447304,	'vmadmin',	'$pbkdf2-sha256$25000$CJFyQkqFAU97wL7KXf3Pvg$YpqUDsHifAhHSxI.w7IXpPER0xVQyF62x8bzQzORa.0',	'13',	0,	0,	0,	'',	'',	'',	'',	'',	'',	'',	'',	1529447016,	1,	'',	0,	'',	NULL,	'',	'',	'',	'',	'',	'',	'0',	'',	1529447037,	1529449562,	'',	'');

DROP TABLE IF EXISTS `tx_vmclub_domain_model_club`;
CREATE TABLE `tx_vmclub_domain_model_club` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `club_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_short_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_founding_year` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_street` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_zip_code` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_city` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_phone` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_email` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_website` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_tax_office` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_tax_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_vat_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_registration_court` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_registration_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_bankname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_i_b_a_n` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_b_i_c` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_d_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_organisation` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_organisation_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_logo` int(10) unsigned NOT NULL DEFAULT '0',
  `club_social_media_facebook` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_social_media_twitter` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_social_media_google` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_social_media_instagram` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `club_social_media_printerest` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tstamp` int(10) unsigned NOT NULL DEFAULT '0',
  `crdate` int(10) unsigned NOT NULL DEFAULT '0',
  `cruser_id` int(10) unsigned NOT NULL DEFAULT '0',
  `deleted` smallint(5) unsigned NOT NULL DEFAULT '0',
  `starttime` int(10) unsigned NOT NULL DEFAULT '0',
  `endtime` int(10) unsigned NOT NULL DEFAULT '0',
  `t3ver_oid` int(11) NOT NULL DEFAULT '0',
  `t3ver_id` int(11) NOT NULL DEFAULT '0',
  `t3ver_wsid` int(11) NOT NULL DEFAULT '0',
  `t3ver_label` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `t3ver_state` smallint(6) NOT NULL DEFAULT '0',
  `t3ver_stage` int(11) NOT NULL DEFAULT '0',
  `t3ver_count` int(11) NOT NULL DEFAULT '0',
  `t3ver_tstamp` int(11) NOT NULL DEFAULT '0',
  `t3ver_move_id` int(11) NOT NULL DEFAULT '0',
  `sys_language_uid` int(11) NOT NULL DEFAULT '0',
  `l10n_parent` int(11) NOT NULL DEFAULT '0',
  `l10n_diffsource` mediumblob,
  `l10n_state` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`),
  KEY `language` (`l10n_parent`,`sys_language_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


DROP TABLE IF EXISTS `tx_vmmember_domain_model_member`;
CREATE TABLE `tx_vmmember_domain_model_member` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `member_lastname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_firstname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_form_of_address` int(11) NOT NULL DEFAULT '0',
  `member_title` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_street` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_zip_code` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_city` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_country_zone` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_country` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_phone1` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_phone2` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_mobile` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_email` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_birthday` int(11) NOT NULL DEFAULT '0',
  `member_wedding_date` int(11) NOT NULL DEFAULT '0',
  `member_marital_status` int(11) NOT NULL DEFAULT '0',
  `member_payment_interval` int(11) NOT NULL DEFAULT '0',
  `member_payment_method` int(11) NOT NULL DEFAULT '0',
  `member_first_payment_date` int(11) NOT NULL DEFAULT '0',
  `member_account_owner` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_i_b_a_n` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_b_i_c` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_mandate_reference` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_mandate_valid` int(11) NOT NULL DEFAULT '0',
  `member_copy_mandate` int(10) unsigned NOT NULL DEFAULT '0',
  `member_note` text COLLATE utf8_unicode_ci NOT NULL,
  `member_i_d` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_entry_date` int(11) NOT NULL DEFAULT '0',
  `member_leaving_date` int(11) NOT NULL DEFAULT '0',
  `member_leaving` smallint(5) unsigned NOT NULL DEFAULT '0',
  `member_reason_for_leaving` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_photo` int(10) unsigned NOT NULL DEFAULT '0',
  `membership_application` int(10) unsigned NOT NULL DEFAULT '0',
  `membership_resignation` int(10) unsigned NOT NULL DEFAULT '0',
  `member_attachments` int(10) unsigned NOT NULL DEFAULT '0',
  `member_dashboard_layout` text COLLATE utf8_unicode_ci NOT NULL,
  `member_is_admin` smallint(5) unsigned NOT NULL DEFAULT '0',
  `member_folder` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `member_vita` int(10) unsigned NOT NULL DEFAULT '0',
  `member_edit_history` int(10) unsigned NOT NULL DEFAULT '0',
  `member_status` int(10) unsigned DEFAULT '0',
  `member_contribution_rate` int(10) unsigned DEFAULT '0',
  `member_salutation` int(10) unsigned DEFAULT '0',
  `member_departments` int(10) unsigned NOT NULL DEFAULT '0',
  `member_has_family` int(10) unsigned NOT NULL DEFAULT '0',
  `member_login` int(10) unsigned DEFAULT '0',
  `tstamp` int(10) unsigned NOT NULL DEFAULT '0',
  `crdate` int(10) unsigned NOT NULL DEFAULT '0',
  `cruser_id` int(10) unsigned NOT NULL DEFAULT '0',
  `deleted` smallint(5) unsigned NOT NULL DEFAULT '0',
  `hidden` smallint(5) unsigned NOT NULL DEFAULT '0',
  `starttime` int(10) unsigned NOT NULL DEFAULT '0',
  `endtime` int(10) unsigned NOT NULL DEFAULT '0',
  `t3ver_oid` int(11) NOT NULL DEFAULT '0',
  `t3ver_id` int(11) NOT NULL DEFAULT '0',
  `t3ver_wsid` int(11) NOT NULL DEFAULT '0',
  `t3ver_label` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `t3ver_state` smallint(6) NOT NULL DEFAULT '0',
  `t3ver_stage` int(11) NOT NULL DEFAULT '0',
  `t3ver_count` int(11) NOT NULL DEFAULT '0',
  `t3ver_tstamp` int(11) NOT NULL DEFAULT '0',
  `t3ver_move_id` int(11) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT '0',
  `sys_language_uid` int(11) NOT NULL DEFAULT '0',
  `l10n_parent` int(11) NOT NULL DEFAULT '0',
  `l10n_diffsource` mediumblob,
  `l10n_state` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`),
  KEY `language` (`l10n_parent`,`sys_language_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `tx_vmmember_domain_model_member` (`uid`, `pid`, `member_lastname`, `member_firstname`, `member_form_of_address`, `member_title`, `member_street`, `member_zip_code`, `member_city`, `member_country_zone`, `member_country`, `member_phone1`, `member_phone2`, `member_mobile`, `member_email`, `member_birthday`, `member_wedding_date`, `member_marital_status`, `member_payment_interval`, `member_payment_method`, `member_first_payment_date`, `member_account_owner`, `member_i_b_a_n`, `member_b_i_c`, `member_mandate_reference`, `member_mandate_valid`, `member_copy_mandate`, `member_note`, `member_i_d`, `member_entry_date`, `member_leaving_date`, `member_leaving`, `member_reason_for_leaving`, `member_photo`, `membership_application`, `membership_resignation`, `member_attachments`, `member_dashboard_layout`, `member_is_admin`, `member_folder`, `member_vita`, `member_edit_history`, `member_status`, `member_contribution_rate`, `member_salutation`, `member_departments`, `member_has_family`, `member_login`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `hidden`, `starttime`, `endtime`, `t3ver_oid`, `t3ver_id`, `t3ver_wsid`, `t3ver_label`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `sorting`, `sys_language_uid`, `l10n_parent`, `l10n_diffsource`, `l10n_state`) VALUES
(1,	45,	'Mustermann',	'Max',	0,	'',	'',	'',	'',	'',	'',	'',	'',	'',	'',	0,	0,	0,	0,	0,	0,	'',	'',	'',	'',	0,	0,	'',	'',	0,	0,	0,	'',	1,	0,	0,	0,	'a:2:{s:6:\"layout\";s:8:\"25/50/25\";s:7:\"widgets\";a:11:{i:0;a:2:{s:8:\"widgetID\";s:13:\"WelcomeWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"1\";s:6:\"column\";s:1:\"2\";}}i:1;a:2:{s:8:\"widgetID\";s:20:\"MemberOverviewWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:2;a:2:{s:8:\"widgetID\";s:30:\"MemberDepartmentOverviewWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:3;a:2:{s:8:\"widgetID\";s:20:\"GenderOverviewWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:4;a:2:{s:8:\"widgetID\";s:23:\"BirthdaysOverviewWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:5;a:2:{s:8:\"widgetID\";s:25:\"AnniversaryOverviewWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:6;a:2:{s:8:\"widgetID\";s:24:\"NextEventsOverviewWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:7;a:2:{s:8:\"widgetID\";s:25:\"NextEventsWithClubsWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:8;a:2:{s:8:\"widgetID\";s:13:\"MyTasksWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:9;a:2:{s:8:\"widgetID\";s:18:\"OverdueTasksWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}i:10;a:2:{s:8:\"widgetID\";s:22:\"SmartVereinNewsWidget\";s:14:\"widgetSettings\";a:2:{s:6:\"active\";s:1:\"0\";s:6:\"column\";s:1:\"1\";}}}}',	0,	'Max_Mustermann',	0,	0,	0,	0,	0,	0,	0,	1,	1529448431,	1529447016,	1,	0,	0,	0,	0,	0,	0,	0,	'',	0,	0,	0,	0,	0,	256,	0,	0,	'a:50:{s:16:\"sys_language_uid\";N;s:6:\"hidden\";N;s:15:\"member_lastname\";N;s:16:\"member_firstname\";N;s:22:\"member_form_of_address\";N;s:12:\"member_title\";N;s:13:\"member_street\";N;s:15:\"member_zip_code\";N;s:11:\"member_city\";N;s:19:\"member_country_zone\";N;s:14:\"member_country\";N;s:13:\"member_phone1\";N;s:13:\"member_phone2\";N;s:13:\"member_mobile\";N;s:12:\"member_email\";N;s:15:\"member_birthday\";N;s:19:\"member_wedding_date\";N;s:21:\"member_marital_status\";N;s:23:\"member_payment_interval\";N;s:21:\"member_payment_method\";N;s:25:\"member_first_payment_date\";N;s:20:\"member_account_owner\";N;s:14:\"member_i_b_a_n\";N;s:12:\"member_b_i_c\";N;s:24:\"member_mandate_reference\";N;s:20:\"member_mandate_valid\";N;s:19:\"member_copy_mandate\";N;s:11:\"member_note\";N;s:10:\"member_i_d\";N;s:17:\"member_entry_date\";N;s:19:\"member_leaving_date\";N;s:14:\"member_leaving\";N;s:25:\"member_reason_for_leaving\";N;s:12:\"member_photo\";N;s:22:\"membership_application\";N;s:22:\"membership_resignation\";N;s:18:\"member_attachments\";N;s:23:\"member_dashboard_layout\";N;s:15:\"member_is_admin\";N;s:13:\"member_folder\";N;s:11:\"member_vita\";N;s:19:\"member_edit_history\";N;s:13:\"member_status\";N;s:24:\"member_contribution_rate\";N;s:17:\"member_salutation\";N;s:18:\"member_departments\";N;s:17:\"member_has_family\";N;s:12:\"member_login\";N;s:9:\"starttime\";N;s:7:\"endtime\";N;}',	NULL);
