<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vm_member"
 *
 * Auto generated by Extension Builder 2018-03-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SmartVerein - Member management',
    'description' => 'Member management module for SmartVerein.',
    'category' => 'plugin',
    'author' => 'Typo3graf Developer-Team',
    'author_email' => 'development@typo3graf.de',
    'author_company' => 'Typo3graf media-agentur',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => 'fileadmin/smartverein/mitglieder/Max_Mustermann, fileadmin/smartverein/abteilungen',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'felogin' => '*'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
