<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vm_club"
 *
 * Auto generated by Extension Builder 2018-03-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SmartVerein - Club module',
    'description' => 'Club module for SmartVerein.',
    'category' => 'plugin',
    'author' => 'Typo3graf Developer-Team',
    'author_email' => 'development@typo3gtraf.de',
    'author_company' => 'Typo3graf media-agentur',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => 'fileadmin/smartverein/verein',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'vm_base' => '*',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
